In [ ]:
import pandas as pd

In [ ]:
#########EDUCATION DATA CLEANING#########

In [2]:
edu = pd.read_csv('Education_Final.csv')

In [3]:
edu.head()

,school_id,school_name,street_address,city,state,zip_code,enrollment,phone_number,locale_code,school_type,school_level,lowest_grade,highest_grade,school_status
0,10000200277,SEQUOYAH SCH - CHALKVILLE CAMPUS,P O BOX 9486,BIRMINGHAM,AL,35220,0,(205) 680-8574,41,4,3,07,12,1
1,10000201402,EUFAULA SCH - EUFAULA CAMPUS,315 OUTBACK ROAD,CLAYTON,AL,36016,0,(334) 687-4441,42,4,4,03,12,1
2,10000201667,CAMPS,P O BOX 66,MT MEIGS,AL,36057,0,(334) 215-3850,41,4,3,07,12,1
3,10000201670,DET CTR,P O BOX 66,MT MEIGS,AL,36057,0,(334) 215-3850,41,4,3,07,12,1
4,10000201705,WALLACE SCH - MT MEIGS CAMPUS,P O BOX 66,MOUNT MEIGS,AL,36057,0,(334) 215-6039,41,4,3,07,12,1

In [4]:
edu.dtypes

school_id          int64
school_name       object
street_address    object
city              object
state             object
zip_code           int64
enrollment         int64
phone_number      object
locale_code       object
school_type        int64
school_level      object
lowest_grade      object
highest_grade     object
school_status      int64
dtype: object

In [ ]:
## 原始edu中有103959
len(edu)

103959

In [5]:
print(edu['school_level'].unique())
print(edu['lowest_grade'].unique())
print(edu['highest_grade'].unique())

['3' '4' 'N' '2' '1']
['07' '03' 'N' '09' '05' 'KG' 'PK' '10' '06' '02' '04' '08' '01' '12' '11'
 'UG']
['12' 'N' '08' '06' '04' 'KG' 'PK' '02' '05' '09' '03' '01' '07' '11' 'UG'
 '10']

In [ ]:
print((edu['school_level'] == 'N').sum())
print((edu['lowest_grade'] == 'N').sum())
print((edu['highest_grade'] == 'N').sum())

4077
2236
2236

In [12]:
print((edu['lowest_grade'] == 'PK').sum())
print((edu['highest_grade'] == 'PK').sum())

28133
1061

In [ ]:
# MAP RULE:
# N:删除
# KG:00
# PK:000
# UG:13

edu.drop(edu[edu['school_level'] == 'N'].index, inplace=True)
edu.drop(edu[edu['lowest_grade'] == 'N'].index, inplace=True)
edu.drop(edu[edu['highest_grade'] == 'N'].index, inplace=True)

edu['lowest_grade'] = edu['lowest_grade'].replace('KG', '00')
edu['lowest_grade'] = edu['lowest_grade'].replace('PK', '000')
edu['highest_grade'] = edu['highest_grade'].replace('KG', '00')
edu['highest_grade'] = edu['highest_grade'].replace('PK', '000')
edu['lowest_grade'] = edu['lowest_grade'].replace('UG', '13')
edu['highest_grade'] = edu['highest_grade'].replace('UG', '13')

In [17]:
print(edu['school_level'].unique())
print(edu['lowest_grade'].unique())
print(edu['highest_grade'].unique())

['3' '4' '2' '1']
['07' '03' '09' '05' '00' '000' '10' '06' '02' '04' '08' '01' '12' '11'
 '13']
['12' '08' '06' '04' '00' '02' '05' '09' '03' '01' '07' '11' '000' '13'
 '10']

In [ ]:
#清理完之后有 99882
# len(edu)

99882

In [ ]:
# Phone Number Cleaning
edu['phone_number'].apply(lambda x: isinstance(x, str)).sum()

np.int64(99882)

In [ ]:
print(edu['school_level'].value_counts(dropna=False))
print(edu['lowest_grade'].value_counts(dropna=False))
print(edu['highest_grade'].value_counts(dropna=False))

school_level
1    54637
3    21154
2    17125
4     6966
Name: count, dtype: int64

In [78]:
# zip_code 转成字符串 school_id 转成字符串
edu['zip_code'] = edu['zip_code'].astype(str)
edu['school_id'] = edu['school_id'].astype(str)

In [79]:
edu.dtypes

school_id         object
school_name       object
street_address    object
city              object
state             object
zip_code          object
enrollment         int64
phone_number      object
locale_code       object
school_type        int64
school_level      object
lowest_grade      object
highest_grade     object
school_status      int64
dtype: object

In [ ]:
######## Real Estate Data Cleaning ########

In [92]:
re = pd.read_csv('Real_Estate_Final.csv')
re

,property_id,broker_id,listing_status,price,bedrooms,bathrooms,lot_size,street_address,city,state,house_size,zip_code,previous_sold_date
0,1,92147.0,for_sale,110000.0,7.0,3.0,0.09,1842706.0,Dorado,PR,1192.0,949.0,2019-06-28
1,4,21163.0,for_sale,525000.0,3.0,3.0,0.45,1813270.0,Agawam,MA,2314.0,1001.0,2014-06-25
2,5,67455.0,for_sale,289900.0,3.0,2.0,0.36,1698080.0,Agawam,MA,1276.0,1001.0,2012-10-12
3,6,97400.0,for_sale,384900.0,3.0,2.0,0.46,1244899.0,Agawam,MA,1476.0,1001.0,1986-11-20
4,7,33714.0,for_sale,199999.0,3.0,2.0,1.76,1745924.0,Agawam,MA,1968.0,1001.0,2008-09-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1084884,1084905,23009.0,sold,359900.0,4.0,2.0,0.33,353094.0,Richland,WA,3600.0,99354.0,2022-03-25
1084885,1084906,18208.0,sold,350000.0,3.0,2.0,0.10,1062149.0,Richland,WA,1616.0,99354.0,2022-03-25
1084886,1084907,76856.0,sold,440000.0,6.0,3.0,0.50,405677.0,Richland,WA,3200.0,99354.0,2022-03-24
1084887,1084908,53618.0,sold,179900.0,2.0,1.0,0.09,761379.0,Richland,WA,933.0,99354.0,2022-03-24
1084888,1084909,108243.0,sold,580000.0,5.0,3.0,0.31,307704.0,Richland,WA,3615.0,99354.0,2022-03-23

In [93]:
re.dtypes

property_id             int64
broker_id             float64
listing_status         object
price                 float64
bedrooms              float64
bathrooms             float64
lot_size              float64
street_address        float64
city                   object
state                  object
house_size            float64
zip_code              float64
previous_sold_date     object
dtype: object

In [94]:
re["city"].value_counts(dropna=False)

city
Houston           15967
Tucson             7551
Phoenix            7379
Los Angeles        6857
Dallas             6695
                  ...
Logsden               1
Falling Spring        1
Hightown              1
Bacova                1
Anatone               1
Name: count, Length: 15101, dtype: int64

In [95]:
# Transfer the zip_code and broker_id into string type for better handling of categorical data
re['zip_code'] = re['zip_code'].astype(int).astype(str)
re['broker_id'] = re['broker_id'].astype(int).astype(str)

In [96]:
# Bedrooms and Bathrooms should be integers, but there are some float values. Let's check how many there are.
re[['bedrooms', 'bathrooms', 'street_address','house_size','price']].apply(lambda x: (x % 1 != 0).sum())

bedrooms          0
bathrooms         0
street_address    0
house_size        0
price             0
dtype: int64

In [97]:
re["bedrooms"] = re['bedrooms'].astype(int)
re["bathrooms"] = re['bathrooms'].astype(int)
re["street_address"] = re['street_address'].astype(int)
re["house_size"] = re['house_size'].astype(int)
re["price"] = re['price'].astype(int)

In [98]:
# 处理日期
re["previous_sold_date"] = pd.to_datetime(re["previous_sold_date"], errors='coerce')

In [99]:
# City 大写
re["city"] = re["city"].str.upper()

In [100]:
# 删除 street_address 
re.drop(columns=['street_address'], inplace=True)

In [101]:
re["property_id"] = re["property_id"].astype(str)

In [102]:
# listing_status 
print(re['listing_status'].value_counts(dropna=False))

# map rule:
# 0: sold
# 1: for_sale

re['listing_status'] = re['listing_status'].map({'sold': 0, 'for_sale': 1})

re['listing_status'].astype(int)

listing_status
sold        606908
for_sale    477981
Name: count, dtype: int64

0          1
1          1
2          1
3          1
4          1
          ..
1084884    0
1084885    0
1084886    0
1084887    0
1084888    0
Name: listing_status, Length: 1084889, dtype: int64

In [103]:
re

,property_id,broker_id,listing_status,price,bedrooms,bathrooms,lot_size,city,state,house_size,zip_code,previous_sold_date
0,1,92147,1,110000,7,3,0.09,DORADO,PR,1192,949,2019-06-28
1,4,21163,1,525000,3,3,0.45,AGAWAM,MA,2314,1001,2014-06-25
2,5,67455,1,289900,3,2,0.36,AGAWAM,MA,1276,1001,2012-10-12
3,6,97400,1,384900,3,2,0.46,AGAWAM,MA,1476,1001,1986-11-20
4,7,33714,1,199999,3,2,1.76,AGAWAM,MA,1968,1001,2008-09-19
...,...,...,...,...,...,...,...,...,...,...,...,...
1084884,1084905,23009,0,359900,4,2,0.33,RICHLAND,WA,3600,99354,2022-03-25
1084885,1084906,18208,0,350000,3,2,0.10,RICHLAND,WA,1616,99354,2022-03-25
1084886,1084907,76856,0,440000,6,3,0.50,RICHLAND,WA,3200,99354,2022-03-24
1084887,1084908,53618,0,179900,2,1,0.09,RICHLAND,WA,933,99354,2022-03-24
1084888,1084909,108243,0,580000,5,3,0.31,RICHLAND,WA,3615,99354,2022-03-23

In [104]:
re.dtypes

property_id                   object
broker_id                     object
listing_status                 int64
price                          int64
bedrooms                       int64
bathrooms                      int64
lot_size                     float64
city                          object
state                         object
house_size                     int64
zip_code                      object
previous_sold_date    datetime64[ns]
dtype: object

In [ ]:
########### IRS Data Cleaning ###########

In [54]:
irs = pd.read_csv('IRS_Final.csv')
irs

,state,zip_code,income_bracket,num_returns,total_income,wage_income,interest_income,dividend_income,capital_gain
0,AL,0,1,659530.0,8735771.0,6827320.0,42624.0,72882.0,25999.0
1,AL,0,2,533640.0,19414110.0,16224681.0,50743.0,94902.0,66098.0
2,AL,0,3,304870.0,18735575.0,14580757.0,55574.0,131776.0,117516.0
3,AL,0,4,193020.0,16734715.0,12416608.0,61091.0,148187.0,144047.0
4,AL,0,5,315700.0,43412373.0,31832034.0,184649.0,548873.0,854015.0
...,...,...,...,...,...,...,...,...,...
166126,WY,99999,2,3100.0,114043.0,81906.0,447.0,1477.0,915.0
166127,WY,99999,3,2130.0,131073.0,87480.0,361.0,1747.0,1550.0
166128,WY,99999,4,1620.0,140490.0,91966.0,513.0,1865.0,1379.0
166129,WY,99999,5,2710.0,370344.0,238062.0,1627.0,6967.0,12078.0
166130,WY,99999,6,1070.0,710050.0,125905.0,15439.0,57741.0,133003.0

In [59]:
irs.dtypes

state               object
zip_code             int64
income_bracket       int64
num_returns        float64
total_income       float64
wage_income        float64
interest_income    float64
dividend_income    float64
capital_gain       float64
dtype: object

In [ ]:
float_cols = ['num_returns', 'total_income', 'wage_income', 'interest_income', 'dividend_income', 'capital_gain']

for col in float_cols:
    has_decimal = (irs[col] % 1 != 0).sum()
    print(f"{col}: {has_decimal} 个有小数")

num_returns: 0 个有小数
total_income: 0 个有小数
wage_income: 0 个有小数
interest_income: 0 个有小数
dividend_income: 0 个有小数
capital_gain: 0 个有小数

In [61]:
for col in float_cols:
    irs[col] = irs[col].fillna(0).astype(int)

In [67]:
# zipcode 转成字符串
irs['zip_code'] = irs['zip_code'].astype(int).astype(str)

In [68]:
irs.dtypes

state              object
zip_code           object
income_bracket      int64
num_returns         int64
total_income        int64
wage_income         int64
interest_income     int64
dividend_income     int64
capital_gain        int64
dtype: object

In [ ]:
######### 保存第二次的数据 #########

In [ ]:
# edu.to_csv('DC2/Education_Cleaned.csv', index=False)
# re.to_csv('DC2/Real_Estate_Cleaned.csv', index=False)
# irs.to_csv('DC2/IRS_Cleaned.csv', index=False)