In [9]:
import pandas as pd
import numpy as np

IRS = pd.read_csv("../IRS.csv")
IRS

,STATEFIPS,STATE,zipcode,agi_stub,N1,mars1,MARS2,MARS4,ELF,CPREP,...,N85300,A85300,N11901,A11901,N11900,A11900,N11902,A11902,N12000,A12000
0,1,AL,0,1,659530.0,422590.0,71000.0,154700.0,610780.0,24340.0,...,0.0,0.0,63060.0,54280.0,543620.0,1559881.0,541480.0,1552563.0,2250.0,5031.0
1,1,AL,0,2,533640.0,276250.0,101050.0,141040.0,499310.0,15050.0,...,0.0,0.0,100320.0,130848.0,430380.0,1339883.0,427830.0,1329439.0,2780.0,8556.0
2,1,AL,0,3,304870.0,134050.0,109980.0,51600.0,286110.0,9600.0,...,0.0,0.0,88750.0,186002.0,216080.0,585162.0,212990.0,573080.0,4520.0,12589.0
3,1,AL,0,4,193020.0,56350.0,113100.0,19090.0,181390.0,4530.0,...,0.0,0.0,67040.0,189833.0,124860.0,403052.0,121760.0,388581.0,2840.0,12190.0
4,1,AL,0,5,315700.0,45000.0,252660.0,12180.0,297930.0,9000.0,...,140.0,63.0,138270.0,657283.0,177730.0,748507.0,169080.0,671684.0,10940.0,80141.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166126,56,WY,99999,2,3100.0,1860.0,790.0,390.0,2960.0,60.0,...,0.0,0.0,580.0,688.0,2380.0,6080.0,2330.0,5841.0,50.0,75.0
166127,56,WY,99999,3,2130.0,1000.0,860.0,210.0,1990.0,70.0,...,0.0,0.0,530.0,1168.0,1500.0,4055.0,1440.0,3818.0,30.0,35.0
166128,56,WY,99999,4,1620.0,530.0,960.0,120.0,1570.0,30.0,...,0.0,0.0,460.0,1390.0,1070.0,3482.0,1010.0,3211.0,50.0,108.0
166129,56,WY,99999,5,2710.0,550.0,2070.0,90.0,2610.0,60.0,...,0.0,0.0,1020.0,5376.0,1600.0,7849.0,1440.0,6455.0,170.0,1011.0
166130,56,WY,99999,6,1070.0,220.0,850.0,30.0,1040.0,50.0,...,660.0,8424.0,520.0,23106.0,470.0,49944.0,220.0,11191.0,280.0,31649.0

In [11]:
real_estate = pd.read_csv('../realtor-data.csv')
real_estate

,brokered_by,status,price,bed,bath,acre_lot,street,city,state,zip_code,house_size,prev_sold_date
0,103378.0,for_sale,105000.0,3.0,2.0,0.12,1962661.0,Adjuntas,Puerto Rico,601.0,920.0,NaN
1,52707.0,for_sale,80000.0,4.0,2.0,0.08,1902874.0,Adjuntas,Puerto Rico,601.0,1527.0,NaN
2,103379.0,for_sale,67000.0,2.0,1.0,0.15,1404990.0,Juana Diaz,Puerto Rico,795.0,748.0,NaN
3,31239.0,for_sale,145000.0,4.0,2.0,0.10,1947675.0,Ponce,Puerto Rico,731.0,1800.0,NaN
4,34632.0,for_sale,65000.0,6.0,2.0,0.05,331151.0,Mayaguez,Puerto Rico,680.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2226377,23009.0,sold,359900.0,4.0,2.0,0.33,353094.0,Richland,Washington,99354.0,3600.0,2022-03-25
2226378,18208.0,sold,350000.0,3.0,2.0,0.10,1062149.0,Richland,Washington,99354.0,1616.0,2022-03-25
2226379,76856.0,sold,440000.0,6.0,3.0,0.50,405677.0,Richland,Washington,99354.0,3200.0,2022-03-24
2226380,53618.0,sold,179900.0,2.0,1.0,0.09,761379.0,Richland,Washington,99354.0,933.0,2022-03-24
2226381,108243.0,sold,580000.0,5.0,3.0,0.31,307704.0,Richland,Washington,99354.0,3615.0,2022-03-23

In [13]:
crime = pd.read_csv('../US_Crime_DataSet.csv')
crime

/var/folders/qr/4hkv36z110zfv47xtg0vv66w0000gn/T/ipykernel_65204/1621791375.py:1: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  crime = pd.read_csv('../US_Crime_DataSet.csv')

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
0,1,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,January,1,Murder or Manslaughter,...,Unknown,Male,15,Native American/Alaska Native,Unknown,Acquaintance,Blunt Object,0,0,FBI
1,2,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,March,1,Murder or Manslaughter,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0,0,FBI
2,3,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,March,2,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Unknown,0,0,FBI
3,4,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,April,1,Murder or Manslaughter,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0,0,FBI
4,5,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,April,2,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Unknown,0,1,FBI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638449,638450,WY01500,Park County,Sheriff,Park,Wyoming,2014,January,1,Murder or Manslaughter,...,Hispanic,Unknown,0,Unknown,Unknown,Unknown,Handgun,0,0,FBI
638450,638451,WY01700,Sheridan County,Sheriff,Sheridan,Wyoming,2014,June,1,Murder or Manslaughter,...,Unknown,Male,57,White,Unknown,Acquaintance,Handgun,0,0,FBI
638451,638452,WY01701,Sheridan,Municipal Police,Sheridan,Wyoming,2014,September,1,Murder or Manslaughter,...,Unknown,Female,22,Asian/Pacific Islander,Unknown,Daughter,Suffocation,0,0,FBI
638452,638453,WY01800,Sublette County,Sheriff,Sublette,Wyoming,2014,December,1,Murder or Manslaughter,...,Not Hispanic,Male,31,White,Not Hispanic,Stranger,Knife,0,1,FBI
638453,638454,WY01902,Rock Springs,Municipal Police,Sweetwater,Wyoming,2014,September,1,Murder or Manslaughter,...,Not Hispanic,Female,24,White,Not Hispanic,Daughter,Blunt Object,0,1,FBI

In [ ]:
Education1 = pd.read_csv('../sc091a_csv/sc091aai.csv')
Education1

,ncessch,schnam09,mstree09,mcity09,mstate09,mzip09,mzip409,member09,phone09,ulocal09,type09,level09,gslo09,gshi09,status09
0,10000200277,SEQUOYAH SCH - CHALKVILLE CAMPUS,P O BOX 9486,BIRMINGHAM,AL,35220,486.0,0,(205) 680-8574,41,4,3,07,12,1
1,10000201402,EUFAULA SCH - EUFAULA CAMPUS,315 OUTBACK ROAD,CLAYTON,AL,36016,NaN,0,(334) 687-4441,42,4,4,03,12,1
2,10000201667,CAMPS,P O BOX 66,MT MEIGS,AL,36057,NaN,0,(334) 215-3850,41,4,3,07,12,1
3,10000201670,DET CTR,P O BOX 66,MT MEIGS,AL,36057,NaN,0,(334) 215-3850,41,4,3,07,12,1
4,10000201705,WALLACE SCH - MT MEIGS CAMPUS,P O BOX 66,MOUNT MEIGS,AL,36057,66.0,0,(334) 215-6039,41,4,3,07,12,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35286,199901900777,GRAND ELEMENTARY SCHOOL,PO BOX 79,BOXHOLM,IA,50040,79.0,120,(515) 846-6214,42,1,2,04,06,1
35287,199901901259,IOWA CENTRAL CHARTER HIGH SCHOOL,PO BOX 49,BURNSIDE,IA,50521,49.0,0,(515) 359-2235,42,1,3,09,12,1
35288,199901902075,SOUTHEAST WEBSTER-GRAND HIGH SCHOOL,PO BOX 49,BURNSIDE,IA,50521,49.0,181,(515) 359-2235,42,1,3,09,12,1
35289,199901902076,SOUTHEAST WEBSTER JUNIOR HIGH,PO BOX 49,BURNSIDE,IA,50521,49.0,72,(515) 359-2235,42,1,2,07,08,1
35290,199901902077,DAYTON CENTER,BOX 26,DAYTON,IA,50530,NaN,192,(515) 547-2314,42,1,1,PK,03,1

In [16]:
Education2 = pd.read_csv('../sc091a_csv/sc091akn.csv')
Education2

,ncessch,schnam09,mstree09,mcity09,mstate09,mzip09,mzip409,member09,phone09,ulocal09,type09,level09,gslo09,gshi09,status09
0,200000100523,SOUTHEAST SALINE HIGH,5056 E. K-4 HIGHWAY,GYPSUM,KS,67448,9762.0,359,(785) 536-4286,42,1,3,07,12,1
1,200000100524,SOUTHEAST SALINE ELEM,5056 E K-4 HIGHWAY,GYPSUM,KS,67448,NaN,349,(785) 536-4215,42,1,1,KG,06,1
2,200000200907,SODERSTROM ELEM,227 N WASHINGTON,LINDSBORG,KS,67456,2129.0,274,(785) 227-2945,33,1,1,KG,04,1
3,200000200909,MARQUETTE ELEM,BOX 309,MARQUETTE,KS,67464,309.0,134,(785) 546-2275,42,1,1,KG,08,1
4,200000201467,LINDSBORG MIDDLE SCHOOL,401 N CEDAR,LINDSBORG,KS,67456,1900.0,253,(785) 227-4249,41,1,2,05,08,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33538,388066000722,SOUTHEAST REGION CAREER & TECH CENTER,2101 9TH ST N,WAHPETON,ND,58075,3015.0,0,(701) 642-8701,41,3,3,09,12,1
33539,388068000720,JAMES VALLEY AREA CAREER & TECH CENTER,910 12TH AVE NE,JAMESTOWN,ND,58401,6513.0,0,(701) 252-8841,41,3,3,09,12,1
33540,388070000723,NORTH VALLEY AREA CAREER & TECH CENTER,1540 SCHOOL RD,GRAFTON,ND,58237,1715.0,0,(701) 352-3705,33,3,3,09,12,1
33541,388072000760,BISMARCK SPEC ED UNIT,806 N WASHINGTON ST,BISMARCK,ND,58501,3623.0,-2,(701) 323-4028,13,2,N,N,N,1
33542,388075000046,BISMARCK TECH CENTER,PO BOX 5587,BISMARCK,ND,58506,5587.0,0,(701) 224-5596,13,3,3,09,12,1

In [17]:
Education3 = pd.read_csv('../sc091a_csv/sc091aow.csv')
Education3

,ncessch,schnam09,mstree09,mcity09,mstate09,mzip09,mzip409,member09,phone09,ulocal09,type09,level09,gslo09,gshi09,status09
0,390000104681,OHIO SCHOOL FOR THE DEAF,500 MORSE RD,COLUMBUS,OH,43214,1833.0,65,(614) 728-1424,11,2,3,09,12,1
1,390000104682,OHIO SCHOOL FOR THE DEAF,500 MORSE RD,COLUMBUS,OH,43214,1833.0,36,(614) 728-1424,11,2,1,PK,05,1
2,390000104683,OHIO SCHOOL FOR THE DEAF,500 MORSE RD,COLUMBUS,OH,43214,1833.0,18,(614) 728-1424,11,2,2,06,08,1
3,390000204684,STATE SCHOOL FOR THE BLIND,5220 N HIGH ST,COLUMBUS,OH,43214,1240.0,80,(614) 752-1359,11,2,3,07,12,1
4,390000204685,STATE SCHOOL FOR THE BLIND,5220 N HIGH ST,COLUMBUS,OH,43214,1240.0,46,(614) 752-1359,11,2,1,KG,06,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35120,780003000025,GLADYS A. ABRAHAM ELEMENTARY SCHOOL,68A ESTATE LINDBERG,SAINT THOMAS,VI,802,NaN,414,(340) 774-7385,41,1,1,KG,06,1
35121,780003000026,ULLA F MULLER ELEMENTARY SCHOOL,7B ESTATE CONTANT,SAINT THOMAS,VI,802,NaN,451,(340) 774-0059,33,1,1,KG,06,1
35122,780003000027,YVONNE BOWSKY ELEMENTARY SCHOOL,15B & 16 ESTATE MANDAHL,SAINT THOMAS,VI,802,NaN,428,(340) 775-3220,33,1,1,KG,06,1
35123,780003000033,CANCRYN JUNIOR HIGH SCHOOL,1 CROWN BAY,SAINT THOMAS,VI,804,NaN,585,(340) 774-4540,33,1,2,07,08,1
35124,780003000034,BERTHA BOSCHULTE JUNIOR HIGH,9-1 & 12A BOVONI (WESTERN),SAINT THOMAS,VI,802,NaN,606,(340) 775-4222,33,1,2,06,08,1

In [ ]:
Education = pd.concat([Education1, Education2, Education3], ignore_index=True)
Education.head()
Education.info()
Education.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103959 entries, 0 to 103958
Data columns (total 15 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   ncessch   103959 non-null  int64
 1   schnam09  103959 non-null  object
 2   mstree09  103959 non-null  object
 3   mcity09   103959 non-null  object
 4   mstate09  103959 non-null  object
 5   mzip09    103959 non-null  int64
 6   mzip409   79562 non-null   float64
 7   member09  103959 non-null  int64
 8   phone09   103959 non-null  object
 9   ulocal09  103959 non-null  object
 10  type09    103959 non-null  int64
 11  level09   103959 non-null  object
 12  gslo09    103959 non-null  object
 13  gshi09    103959 non-null  object
 14  status09  103959 non-null  int64
dtypes: float64(1), int64(5), object(9)
memory usage: 11.9+ MB

ncessch         0
schnam09        0
mstree09        0
mcity09         0
mstate09        0
mzip09          0
mzip409     24397
member09        0
phone09         0
ulocal09        0
type09          0
level09         0
gslo09          0
gshi09          0
status09        0
dtype: int64

In [34]:
# drop zip4 column of Education
Education.drop(columns=['mzip409'], inplace=True)

In [27]:
IRS.isnull().sum().any()

np.False_

In [30]:
real_estate.info()
real_estate.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2226382 entries, 0 to 2226381
Data columns (total 12 columns):
 #   Column          Dtype
---  ------          -----
 0   brokered_by     float64
 1   status          object
 2   price           float64
 3   bed             float64
 4   bath            float64
 5   acre_lot        float64
 6   street          float64
 7   city            object
 8   state           object
 9   zip_code        float64
 10  house_size      float64
 11  prev_sold_date  object
dtypes: float64(8), object(4)
memory usage: 203.8+ MB

brokered_by         4533
status                 0
price               1541
bed               481317
bath              511771
acre_lot          325589
street             10866
city                1407
state                  8
zip_code             299
house_size        568484
prev_sold_date    734297
dtype: int64

In [32]:
# drop null of real_estate
real_estate.dropna(inplace=True)
real_estate.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1084909 entries, 502 to 2226381
Data columns (total 12 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   brokered_by     1084909 non-null  float64
 1   status          1084909 non-null  object
 2   price           1084909 non-null  float64
 3   bed             1084909 non-null  float64
 4   bath            1084909 non-null  float64
 5   acre_lot        1084909 non-null  float64
 6   street          1084909 non-null  float64
 7   city            1084909 non-null  object
 8   state           1084909 non-null  object
 9   zip_code        1084909 non-null  float64
 10  house_size      1084909 non-null  float64
 11  prev_sold_date  1084909 non-null  object
dtypes: float64(8), object(4)
memory usage: 107.6+ MB

In [35]:
state_abbrev = {
    'Alabama': 'AL', 'Alaska': 'AK', 'Arizona': 'AZ', 'Arkansas': 'AR',
    'California': 'CA', 'Colorado': 'CO', 'Connecticut': 'CT', 'Delaware': 'DE',
    'Florida': 'FL', 'Georgia': 'GA', 'Hawaii': 'HI', 'Idaho': 'ID',
    'Illinois': 'IL', 'Indiana': 'IN', 'Iowa': 'IA', 'Kansas': 'KS',
    'Kentucky': 'KY', 'Louisiana': 'LA', 'Maine': 'ME', 'Maryland': 'MD',
    'Massachusetts': 'MA', 'Michigan': 'MI', 'Minnesota': 'MN', 'Mississippi': 'MS',
    'Missouri': 'MO', 'Montana': 'MT', 'Nebraska': 'NE', 'Nevada': 'NV',
    'New Hampshire': 'NH', 'New Jersey': 'NJ', 'New Mexico': 'NM', 'New York': 'NY',
    'North Carolina': 'NC', 'North Dakota': 'ND', 'Ohio': 'OH', 'Oklahoma': 'OK',
    'Oregon': 'OR', 'Pennsylvania': 'PA', 'Rhode Island': 'RI', 'South Carolina': 'SC',
    'South Dakota': 'SD', 'Tennessee': 'TN', 'Texas': 'TX', 'Utah': 'UT',
    'Vermont': 'VT', 'Virginia': 'VA', 'Washington': 'WA', 'West Virginia': 'WV',
    'Wisconsin': 'WI', 'Wyoming': 'WY', 'District of Columbia': 'DC',
    'Puerto Rico': 'PR'
}

In [36]:
real_estate['state'] = real_estate['state'].map(state_abbrev)

In [40]:
real_estate['state'].value_counts().to_string()

'state\nCA    157724\nFL    107570\nTX    106040\nAZ     50269\nPA     42670\nGA     42384\nWA     41159\nNY     38883\nIL     38473\nVA     38363\nOH     35571\nMD     30527\nMN     27553\nNC     27370\nMA     24866\nOK     22901\nMO     20675\nOR     18430\nNJ     16190\nCO     15219\nMI     14806\nWI     12998\nIA     12747\nTN     12388\nSC     11275\nKY     10868\nAL      9519\nID      9162\nNM      8871\nLA      8266\nAR      8185\nNV      7054\nKS      6722\nCT      6312\nIN      5888\nRI      5224\nDE      4856\nWV      4490\nUT      4146\nNE      2995\nMT      2963\nHI      2899\nDC      2508\nMS      2271\nND      1214\nNH       766\nSD       663\nWY       594\nVT       494\nME       373\nAK       291\nPR       244'

In [43]:
education_rename = {
    'ncessch': 'school_id',
    'schnam09': 'school_name',
    'mstree09': 'street_address',
    'mcity09': 'city',
    'mstate09': 'state',
    'mzip09': 'zip_code',
    'member09': 'enrollment',
    'phone09': 'phone_number',
    'ulocal09': 'locale_code',
    'type09': 'school_type',
    'level09': 'school_level',
    'gslo09': 'lowest_grade',
    'gshi09': 'highest_grade',
    'status09': 'school_status'
}

Education = Education.rename(columns=education_rename)
Education.head()

,school_id,school_name,street_address,city,state,zip_code,enrollment,phone_number,locale_code,school_type,school_level,lowest_grade,highest_grade,school_status
0,10000200277,SEQUOYAH SCH - CHALKVILLE CAMPUS,P O BOX 9486,BIRMINGHAM,AL,35220,0,(205) 680-8574,41,4,3,07,12,1
1,10000201402,EUFAULA SCH - EUFAULA CAMPUS,315 OUTBACK ROAD,CLAYTON,AL,36016,0,(334) 687-4441,42,4,4,03,12,1
2,10000201667,CAMPS,P O BOX 66,MT MEIGS,AL,36057,0,(334) 215-3850,41,4,3,07,12,1
3,10000201670,DET CTR,P O BOX 66,MT MEIGS,AL,36057,0,(334) 215-3850,41,4,3,07,12,1
4,10000201705,WALLACE SCH - MT MEIGS CAMPUS,P O BOX 66,MOUNT MEIGS,AL,36057,0,(334) 215-6039,41,4,3,07,12,1

In [47]:
irs_rename = {
    'STATE': 'state',
    'zipcode': 'zip_code',
    'agi_stub': 'income_bracket',
    'N1': 'num_returns',
    'A00100': 'total_income',
    'A00200': 'wage_income',
    'A00300': 'interest_income',
    'A00600': 'dividend_income',
    'A01000': 'capital_gain'
}

IRS = IRS.rename(columns=irs_rename)
IRS = IRS[['state', 'zip_code', 'income_bracket', 'num_returns', 
           'total_income', 'wage_income', 'interest_income', 
           'dividend_income', 'capital_gain']]


IRS.head()

,state,zip_code,income_bracket,num_returns,total_income,wage_income,interest_income,dividend_income,capital_gain
0,AL,0,1,659530.0,8735771.0,6827320.0,42624.0,72882.0,25999.0
1,AL,0,2,533640.0,19414110.0,16224681.0,50743.0,94902.0,66098.0
2,AL,0,3,304870.0,18735575.0,14580757.0,55574.0,131776.0,117516.0
3,AL,0,4,193020.0,16734715.0,12416608.0,61091.0,148187.0,144047.0
4,AL,0,5,315700.0,43412373.0,31832034.0,184649.0,548873.0,854015.0

In [ ]:
# 重命名
real_estate_rename = {
    'brokered_by': 'broker_id',
    'status': 'listing_status',
    'bed': 'bedrooms',
    'bath': 'bathrooms',
    'acre_lot': 'lot_size',
    'street': 'street_address',
    'prev_sold_date': 'previous_sold_date'
}

real_estate = real_estate.rename(columns=real_estate_rename)

# 创建新的 property_id
real_estate.insert(0, 'property_id', range(1, len(real_estate) + 1))

# 只保留需要的列
real_estate = real_estate[['property_id', 'broker_id', 'listing_status', 'price',
                            'bedrooms', 'bathrooms', 'lot_size', 'street_address',
                            'city', 'state', 'house_size', 'zip_code', 'previous_sold_date']]

ValueError: cannot insert property_id, already exists

In [59]:
real_estate = real_estate.reset_index(drop=True)
real_estate.dropna(inplace=True)
real_estate.head()

,property_id,broker_id,listing_status,price,bedrooms,bathrooms,lot_size,street_address,city,state,house_size,zip_code,previous_sold_date
0,1,92147.0,for_sale,110000.0,7.0,3.0,0.09,1842706.0,Dorado,PR,1192.0,949.0,2019-06-28
1,4,21163.0,for_sale,525000.0,3.0,3.0,0.45,1813270.0,Agawam,MA,2314.0,1001.0,2014-06-25
2,5,67455.0,for_sale,289900.0,3.0,2.0,0.36,1698080.0,Agawam,MA,1276.0,1001.0,2012-10-12
3,6,97400.0,for_sale,384900.0,3.0,2.0,0.46,1244899.0,Agawam,MA,1476.0,1001.0,1986-11-20
4,7,33714.0,for_sale,199999.0,3.0,2.0,1.76,1745924.0,Agawam,MA,1968.0,1001.0,2008-09-19

In [60]:
Education.to_csv('../csv/Education_Final.csv', index=False)
real_estate.to_csv('../csv/Real_Estate_Final.csv', index=False)
IRS.to_csv('../csv/IRS_Final.csv', index=False)